services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
           - /home/umbrel/umbrel/home/Downloads/movies:/home/umbrel/umbrel/home/Downloads/movies
           - /home/umbrel/umbrel/home/Downloads/music:/home/umbrel/umbrel/home/Downloads/music

    restart: always
